/*
 * This is a minimal placeholder configuration file for jansson.
 * The original file is normally generated by the 'configure' script
 * during the library setup to define system-specific constants.
 *
 * This version is based on a standard Linux/POSIX configuration
 * and is suitable for compilation under the C99 standard.
 */

/*
 * Ensure C99 fixed-width integer types (int32_t, uint32_t) are available.
 * These are defined by <stdint.h>, which is fully supported by the C99 standard.
 */
#include <stdint.h>

#ifndef JANSSON_PRIVATE_CONFIG_H
#define JANSSON_PRIVATE_CONFIG_H

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if the system has the type `long long'. */
#define JANSSON_HAVE_LONG_LONG 1

/* Define to 1 if your system has `__GNUC__` defined. */
#define JANSSON_USING_GNUC 1

/* Define to 1 if your system has `visibility("hidden")` defined */
#define JANSSON_HAVE_ATTRIBUTE_VISIBILITY 1

/* Define to 1 if you have <sys/types.h> */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <stdint.h> */
#define HAVE_STDINT_H 1

#endif /* JANSSON_PRIVATE_CONFIG_H */
